name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  animations: ^2.0.11
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  get: ^4.7.2
  google_nav_bar: ^5.0.7
  http: ^1.3.0
  responsive_builder: ^0.7.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
